/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-12-13 02:51:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>Pixel - Digital Agency HTML Template</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"img/core-img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/scss/style.scss\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/scss/_fonts.scss\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/scss/_mixin.scss\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/scss/_responsive.scss\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/scss/_theme_color.scss\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"lds-ellipsis\">\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Header Area Start ##### -->\r\n");
      out.write("    <header class=\"header-area\">\r\n");
      out.write("        <!-- Navbar Area -->\r\n");
      out.write("        <div class=\"pixel-main-menu\" id=\"sticker\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <!-- Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"pixelNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Nav brand -->\r\n");
      out.write("                        <a href=\"index.html\" class=\"nav-brand\"><img src=\"img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Close Button -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                    <li><a href=\"about.html\">About</a></li>\r\n");
      out.write("                                    <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                    <li><a href=\"portfolio.html\">Pages</a>\r\n");
      out.write("                                        <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                            <li><a href=\"services.html\">Services</a>\r\n");
      out.write("                                                <ul class=\"dropdown\">\r\n");
      out.write("                                                    <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                    <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                    <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                    <li><a href=\"portfolio.html\">Portfolio</a>\r\n");
      out.write("                                                        <ul class=\"dropdown\">\r\n");
      out.write("                                                            <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                            <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                            <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                            <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                                            <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                            <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                    <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                            <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                            <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"#\">Mega</a>\r\n");
      out.write("                                        <div class=\"megamenu\">\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("                                                <li><a href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                                <li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Top Social Info -->\r\n");
      out.write("                                <div class=\"top-social-info ml-5\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- ##### Header Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Hero Area Start ##### -->\r\n");
      out.write("    <section class=\"hero-area\">\r\n");
      out.write("        <div class=\"hero-slideshow owl-carousel\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Slide -->\r\n");
      out.write("            <div class=\"single-slide\">\r\n");
      out.write("                <!-- Background Image-->\r\n");
      out.write("                <div class=\"slide-bg-img bg-img\" style=\"background-image: url(img/bg-img/1.jpg);\"></div>\r\n");
      out.write("                <!-- Welcome Text -->\r\n");
      out.write("                <div class=\"container h-100\">\r\n");
      out.write("                    <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                        <div class=\"col-12 col-lg-9\">\r\n");
      out.write("                            <div class=\"welcome-text\">\r\n");
      out.write("                                <h2 data-animation=\"fadeInUp\" data-delay=\"300ms\"><span>Digital Agency</span><br>of the year 2019</h2>\r\n");
      out.write("                                <h4 data-animation=\"fadeInUp\" data-delay=\"500ms\">Visual Identity by John Doe Client: <span>Lorem ipsum</span></h4>\r\n");
      out.write("                                <a href=\"#\" class=\"btn pixel-btn mt-50\" data-animation=\"fadeInUp\" data-delay=\"700ms\">View Project</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Slide -->\r\n");
      out.write("            <div class=\"single-slide\">\r\n");
      out.write("                <!-- Background Image-->\r\n");
      out.write("                <div class=\"slide-bg-img bg-img\" style=\"background-image: url(img/bg-img/2.jpg);\"></div>\r\n");
      out.write("                <!-- Welcome Text -->\r\n");
      out.write("                <div class=\"container h-100\">\r\n");
      out.write("                    <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                        <div class=\"col-12 col-lg-9\">\r\n");
      out.write("                            <div class=\"welcome-text\">\r\n");
      out.write("                                <h2 data-animation=\"fadeInUp\" data-delay=\"300ms\"><span>Creative Agency</span><br>of the year 2019</h2>\r\n");
      out.write("                                <h4 data-animation=\"fadeInUp\" data-delay=\"500ms\">Visual Identity by John Doe Client: <span>Lorem ipsum</span></h4>\r\n");
      out.write("                                <a href=\"#\" class=\"btn pixel-btn mt-50\" data-animation=\"fadeInUp\" data-delay=\"700ms\">View Project</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ##### Hero Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Top Catagory Area Start ##### -->\r\n");
      out.write("    <div class=\"top-catagory-area d-flex flex-wrap\">\r\n");
      out.write("        <!-- Single Catagory -->\r\n");
      out.write("        <div class=\"single-catagory bg-img d-flex align-items-center justify-content-center jarallax\" style=\"background-image: url(img/bg-img/3.jpg);\">\r\n");
      out.write("            <a href=\"#\">Agency</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Single Catagory -->\r\n");
      out.write("        <div class=\"single-catagory bg-img d-flex align-items-center justify-content-center jarallax\" style=\"background-image: url(img/bg-img/4.jpg);\">\r\n");
      out.write("            <a href=\"#\">What We Do?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ##### Top Catagory Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Newsletter Area Start ###### -->\r\n");
      out.write("    <section class=\"nl-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-end\">\r\n");
      out.write("                <div class=\"col-12 col-md-9\">\r\n");
      out.write("                    <div class=\"nl-form mb-100\">\r\n");
      out.write("                        <h4>Stay in touch with us</h4>\r\n");
      out.write("                        <form action=\"#\" method=\"post\">\r\n");
      out.write("                            <input type=\"email\" name=\"nl-email\" id=\"nlEmail\" placeholder=\"Email Address ...\">\r\n");
      out.write("                            <button type=\"submit\" class=\"d-none\"></button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-md-3\">\r\n");
      out.write("                    <div class=\"view-projects-btn text-right mb-100\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn pixel-btn\">View Project</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ##### Newsletter Area End ###### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Portfolio Area Start ###### -->\r\n");
      out.write("    <div class=\"pixel-portfolio-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <!-- Section Heading -->\r\n");
      out.write("                    <div class=\"section-heading text-center wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                        <h2>Made by pixel</h2>\r\n");
      out.write("                        <img src=\"img/core-img/x.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Portfolio Menu -->\r\n");
      out.write("        <div class=\"pixel-projects-menu wow fadeInUp\" data-wow-delay=\"200ms\">\r\n");
      out.write("            <div class=\"text-center portfolio-menu\">\r\n");
      out.write("                <button class=\"btn active\" data-filter=\"*\">All Projects</button>\r\n");
      out.write("                <button class=\"btn\" data-filter=\".visual\">Visual</button>\r\n");
      out.write("                <button class=\"btn\" data-filter=\".add\">Advertising</button>\r\n");
      out.write("                <button class=\"btn\" data-filter=\".web\">Web Development</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"pixel-portfolio\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Single gallery Item -->\r\n");
      out.write("            <div class=\"single_gallery_item visual wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                <img src=\"img/bg-img/5.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"hover-content text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"hover-text\">\r\n");
      out.write("                        <a href=\"img/bg-img/5.jpg\" class=\"zoom-img\"><i class=\"fa fa-eye\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        <h4>Branding Identity</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single gallery Item -->\r\n");
      out.write("            <div class=\"single_gallery_item add wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                <img src=\"img/bg-img/6.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"hover-content text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"hover-text\">\r\n");
      out.write("                        <a href=\"img/bg-img/5.jpg\" class=\"zoom-img\"><i class=\"fa fa-eye\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        <h4>Branding Identity</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single gallery Item -->\r\n");
      out.write("            <div class=\"single_gallery_item web wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                <img src=\"img/bg-img/7.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"hover-content text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"hover-text\">\r\n");
      out.write("                        <a href=\"img/bg-img/5.jpg\" class=\"zoom-img\"><i class=\"fa fa-eye\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        <h4>Branding Identity</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ##### Portfolio Area End ###### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Contact Area Start #####-->\r\n");
      out.write("    <section class=\"contact-area section-padding-100\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <!-- Section Heading -->\r\n");
      out.write("                    <div class=\"section-heading text-center wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                        <h2>Get In Touch</h2>\r\n");
      out.write("                        <img src=\"img/core-img/x.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                    <!-- Contact Form -->\r\n");
      out.write("                    <div class=\"contact-form-area text-center\">\r\n");
      out.write("                        <form action=\"#\" method=\"post\">\r\n");
      out.write("                            <input type=\"text\" name=\"name\" class=\"form-control wow fadeInUp\" data-wow-delay=\"100ms\" placeholder=\"Name\">\r\n");
      out.write("                            <input type=\"email\" name=\"email\" class=\"form-control wow fadeInUp\" data-wow-delay=\"300ms\" placeholder=\"E-mail\">\r\n");
      out.write("                            <input type=\"text\" name=\"subject\" class=\"form-control wow fadeInUp\" data-wow-delay=\"500ms\" placeholder=\"Subject\">\r\n");
      out.write("                            <textarea name=\"message\" class=\"form-control wow fadeInUp\" data-wow-delay=\"700ms\" placeholder=\"Message\"></textarea>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn pixel-btn wow fadeInUp\" data-wow-delay=\"900ms\">Send Message</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ##### Contact Area End #####-->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("    <footer class=\"footer-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Single Footer Widget -->\r\n");
      out.write("                <div class=\"col-12 col-sm-6 col-md-3\">\r\n");
      out.write("                    <div class=\"single-footer-widget mb-100\">\r\n");
      out.write("                        <!-- Footer Logo -->\r\n");
      out.write("                        <a href=\"index.html\" class=\"footer-logo\"><img src=\"img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Single Footer Widget -->\r\n");
      out.write("                <div class=\"col-12 col-md-9 col-lg-8 col-xl-7\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- Single Footer Widget -->\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"single-footer-widget mb-100\">\r\n");
      out.write("                                <h5 class=\"widget-title\">Address</h5>\r\n");
      out.write("                                <p>1530 Doverfield Ave <br> Hacienda Heights, California(CA), 91745</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Footer Widget -->\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"single-footer-widget mb-100\">\r\n");
      out.write("                                <h5 class=\"widget-title\">Support</h5>\r\n");
      out.write("                                <p><i class=\"fa fa-phone\"></i> <br> +01 251 332 331</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Footer Widget -->\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"single-footer-widget mb-100\">\r\n");
      out.write("                                <h5 class=\"widget-title\">Social</h5>\r\n");
      out.write("                                <div class=\"footer-social-info\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Copywrite Area -->\r\n");
      out.write("        <div class=\"copywrite-area\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                        <div class=\"copywrite-content\">\r\n");
      out.write("                            <!-- Copywrite Text -->\r\n");
      out.write("                            <p class=\"copywrite-text\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                        <nav class=\"footer-nav\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                                <li><a href=\"#\">About us</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Services</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Portfolio</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### All Javascript Script ##### -->\r\n");
      out.write("    <!-- jQuery-2.2.4 js -->\r\n");
      out.write("    <script src=\"js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <script src=\"js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins js -->\r\n");
      out.write("    <script src=\"js/plugins/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"js/active.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
